name: Release

on:
  release:
    types: [created]

env:
  TOOL_DEPS_VERSION: '1.10.1.469'
  GRAALVM_VERSION: '19.3.0.java8'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, ubuntu-18.04]
        jdbc_driver: [postgres]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        id: cache
        with:
          path: /root/.m2/
          key: deps-v2-${{ hashFiles('deps.edn') }}
      - uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: ${{ env.GRAALVM_VERSION }}
      - name: Install GraalVM native-image plugin
        run: gu install native-image
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: ${{ env.TOOL_DEPS_VERSION }}
      - name: Compile GraalVM Native Image
        run: |
          echo $JAVA_HOME
          clojure -A:native-image
      - name: Zip as lambda.zip
        run: |
          cp $JAVA_HOME/jre/lib/amd64/libsunec.so .
          cp target/ragtime-cli ragtime-cli
          cp bin/bootstrap bootstrap
          chmod 755 ragtime-cli bootstrap
          zip lambda-${{ matrix.os }}-${{ matrix.jdbc_driver }}.zip bootstrap ragtime-cli libsunec.so
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'lambda-*.zip'